version: 2.1

workflows:
  check-build:
    jobs:
      - shellcheck/check
      - build_docker_image:
          requires:
            - shellcheck/check

orbs:
  shellcheck: circleci/shellcheck@2.2.2

jobs:
  build_docker_image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false # Free does not include caching
      - run:
          name: Build Docker image
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            ./DockerBuildPush.sh